version: '2'
services:
  postgres:
    container_name: postgres
    image: postgres:9.4.1
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  app:
    container_name: ziher
    build: ../
    image: ziher:latest
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - ZIHER_DB_HOST=postgres
      - ZIHER_DB_NAME=ziher_development
      - ZIHER_DB_USERNAME=ziher
      - ZIHER_DB_PASSWORD=ziher
      - SECRET_KEY_BASE=99999999999999998888888877777776666665555544443332211aafb49eb0b8f5b780806cee250dc486ca8e4dde901fd8a96543471d8d2e7f6afcb303e1ed4e
    links:
      - postgres
    read_only: true
    tmpfs:
      - /tmp:exec
      - /usr/local/bundle/gems/passenger-5.2.3/buildout:exec
      - /ziher/log
      - /ziher/tmp
      - /ziher/tmp/pids
      - /root
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
