# encoding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create!([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create!(name: 'Emanuel', city: cities.first)

skladki_2007 = Category.create!(name: 'Składki', is_expense: false, year: 2007)
darowizny_2007 = Category.create!(name: 'Darowizny', is_expense: false, year: 2007)
akcje_zarobkowe_2007 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2007)
pozostale_2007 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2007)
jeden_procent_2007 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2007)
wyposazenie_2007 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2007)
materialy_2007 = Category.create!(name: 'Materiały', is_expense: true, year: 2007)
wyzywienie_2007 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2007)
uslugi_2007 = Category.create!(name: 'Usługi', is_expense: true, year: 2007)
transport_2007 = Category.create!(name: 'Transport', is_expense: true, year: 2007)
czynsz_2007 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2007)
ubezpieczenia_2007 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2007)
inne_2007 = Category.create!(name: 'Inne', is_expense: true, year: 2007)
wynagrodzenia_2007 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2007)
skladki_wydatek_2007 = Category.create!(name: 'Składki', is_expense: true, year: 2007)

skladki_2008 = Category.create!(name: 'Składki', is_expense: false, year: 2008)
darowizny_2008 = Category.create!(name: 'Darowizny', is_expense: false, year: 2008)
akcje_zarobkowe_2008 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2008)
pozostale_2008 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2008)
jeden_procent_2008 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2008)
wyposazenie_2008 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2008)
materialy_2008 = Category.create!(name: 'Materiały', is_expense: true, year: 2008)
wyzywienie_2008 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2008)
uslugi_2008 = Category.create!(name: 'Usługi', is_expense: true, year: 2008)
transport_2008 = Category.create!(name: 'Transport', is_expense: true, year: 2008)
czynsz_2008 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2008)
ubezpieczenia_2008 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2008)
inne_2008 = Category.create!(name: 'Inne', is_expense: true, year: 2008)
wynagrodzenia_2008 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2008)
skladki_wydatek_2008 = Category.create!(name: 'Składki', is_expense: true, year: 2008)

skladki_2009 = Category.create!(name: 'Składki', is_expense: false, year: 2009)
darowizny_2009 = Category.create!(name: 'Darowizny', is_expense: false, year: 2009)
akcje_zarobkowe_2009 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2009)
pozostale_2009 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2009)
jeden_procent_2009 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2009)
wyposazenie_2009 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2009)
materialy_2009 = Category.create!(name: 'Materiały', is_expense: true, year: 2009)
wyzywienie_2009 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2009)
uslugi_2009 = Category.create!(name: 'Usługi', is_expense: true, year: 2009)
transport_2009 = Category.create!(name: 'Transport', is_expense: true, year: 2009)
czynsz_2009 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2009)
ubezpieczenia_2009 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2009)
inne_2009 = Category.create!(name: 'Inne', is_expense: true, year: 2009)
wynagrodzenia_2009 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2009)
skladki_wydatek_2009 = Category.create!(name: 'Składki', is_expense: true, year: 2009)

skladki_2010 = Category.create!(name: 'Składki', is_expense: false, year: 2010)
darowizny_2010 = Category.create!(name: 'Darowizny', is_expense: false, year: 2010)
akcje_zarobkowe_2010 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2010)
pozostale_2010 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2010)
jeden_procent_2010 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2010)
wyposazenie_2010 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2010)
materialy_2010 = Category.create!(name: 'Materiały', is_expense: true, year: 2010)
wyzywienie_2010 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2010)
uslugi_2010 = Category.create!(name: 'Usługi', is_expense: true, year: 2010)
transport_2010 = Category.create!(name: 'Transport', is_expense: true, year: 2010)
czynsz_2010 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2010)
ubezpieczenia_2010 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2010)
inne_2010 = Category.create!(name: 'Inne', is_expense: true, year: 2010)
wynagrodzenia_2010 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2010)
skladki_wydatek_2010 = Category.create!(name: 'Składki', is_expense: true, year: 2010)

skladki_2011 = Category.create!(name: 'Składki', is_expense: false, year: 2011)
darowizny_2011 = Category.create!(name: 'Darowizny', is_expense: false, year: 2011)
akcje_zarobkowe_2011 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2011)
pozostale_2011 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2011)
jeden_procent_2011 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2011)
wyposazenie_2011 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2011)
materialy_2011 = Category.create!(name: 'Materiały', is_expense: true, year: 2011)
wyzywienie_2011 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2011)
uslugi_2011 = Category.create!(name: 'Usługi', is_expense: true, year: 2011)
transport_2011 = Category.create!(name: 'Transport', is_expense: true, year: 2011)
czynsz_2011 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2011)
ubezpieczenia_2011 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2011)
inne_2011 = Category.create!(name: 'Inne', is_expense: true, year: 2011)
wynagrodzenia_2011 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2011)
skladki_wydatek_2011 = Category.create!(name: 'Składki', is_expense: true, year: 2011)

skladki_2012 = Category.create!(name: 'Składki', is_expense: false, year: 2012)
darowizny_2012 = Category.create!(name: 'Darowizny', is_expense: false, year: 2012)
akcje_zarobkowe_2012 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2012)
pozostale_2012 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2012)
jeden_procent_2012 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2012)
wyposazenie_2012 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2012)
materialy_2012 = Category.create!(name: 'Materiały', is_expense: true, year: 2012)
wyzywienie_2012 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2012)
uslugi_2012 = Category.create!(name: 'Usługi', is_expense: true, year: 2012)
transport_2012 = Category.create!(name: 'Transport', is_expense: true, year: 2012)
czynsz_2012 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2012)
ubezpieczenia_2012 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2012)
inne_2012 = Category.create!(name: 'Inne', is_expense: true, year: 2012)
wynagrodzenia_2012 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2012)
skladki_wydatek_2012 = Category.create!(name: 'Składki', is_expense: true, year: 2012)

skladki_2013 = Category.create!(name: 'Składki', is_expense: false, year: 2013)
darowizny_2013 = Category.create!(name: 'Darowizny', is_expense: false, year: 2013)
akcje_zarobkowe_2013 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2013)
pozostale_2013 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2013)
jeden_procent_2013 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2013)
wyposazenie_2013 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2013)
materialy_2013 = Category.create!(name: 'Materiały', is_expense: true, year: 2013)
wyzywienie_2013 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2013)
uslugi_2013 = Category.create!(name: 'Usługi', is_expense: true, year: 2013)
transport_2013 = Category.create!(name: 'Transport', is_expense: true, year: 2013)
czynsz_2013 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2013)
ubezpieczenia_2013 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2013)
inne_2013 = Category.create!(name: 'Inne', is_expense: true, year: 2013)
wynagrodzenia_2013 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2013)
skladki_wydatek_2013 = Category.create!(name: 'Składki', is_expense: true, year: 2013)

skladki_2014 = Category.create!(name: 'Składki', is_expense: false, year: 2014)
darowizny_2014 = Category.create!(name: 'Darowizny', is_expense: false, year: 2014)
akcje_zarobkowe_2014 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2014)
pozostale_2014 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2014)
jeden_procent_2014 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2014)
wyposazenie_2014 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2014)
materialy_2014 = Category.create!(name: 'Materiały', is_expense: true, year: 2014)
wyzywienie_2014 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2014)
uslugi_2014 = Category.create!(name: 'Usługi', is_expense: true, year: 2014)
transport_2014 = Category.create!(name: 'Transport', is_expense: true, year: 2014)
czynsz_2014 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2014)
ubezpieczenia_2014 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2014)
inne_2014 = Category.create!(name: 'Inne', is_expense: true, year: 2014)
wynagrodzenia_2014 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2014)
skladki_wydatek_2014 = Category.create!(name: 'Składki', is_expense: true, year: 2014)

skladki_2015 = Category.create!(name: 'Składki', is_expense: false, year: 2015)
darowizny_2015 = Category.create!(name: 'Darowizny', is_expense: false, year: 2015)
akcje_zarobkowe_2015 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2015)
pozostale_2015 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2015)
jeden_procent_2015 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2015)
wyposazenie_2015 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2015)
materialy_2015 = Category.create!(name: 'Materiały', is_expense: true, year: 2015)
wyzywienie_2015 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2015)
uslugi_2015 = Category.create!(name: 'Usługi', is_expense: true, year: 2015)
transport_2015 = Category.create!(name: 'Transport', is_expense: true, year: 2015)
czynsz_2015 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2015)
ubezpieczenia_2015 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2015)
inne_2015 = Category.create!(name: 'Inne', is_expense: true, year: 2015)
wynagrodzenia_2015 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2015)
skladki_wydatek_2015 = Category.create!(name: 'Składki', is_expense: true, year: 2015)

skladki_2016 = Category.create!(name: 'Składki', is_expense: false, year: 2016)
darowizny_2016 = Category.create!(name: 'Darowizny', is_expense: false, year: 2016)
akcje_zarobkowe_2016 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2016)
pozostale_2016 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2016)
jeden_procent_2016 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2016)
wyposazenie_2016 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2016)
materialy_2016 = Category.create!(name: 'Materiały', is_expense: true, year: 2016)
wyzywienie_2016 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2016)
uslugi_2016 = Category.create!(name: 'Usługi', is_expense: true, year: 2016)
transport_2016 = Category.create!(name: 'Transport', is_expense: true, year: 2016)
czynsz_2016 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2016)
ubezpieczenia_2016 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2016)
inne_2016 = Category.create!(name: 'Inne', is_expense: true, year: 2016)
wynagrodzenia_2016 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2016)
skladki_wydatek_2016 = Category.create!(name: 'Składki', is_expense: true, year: 2016)

skladki_2017 = Category.create!(name: 'Składki', is_expense: false, year: 2017)
darowizny_2017 = Category.create!(name: 'Darowizny', is_expense: false, year: 2017)
akcje_zarobkowe_2017 = Category.create!(name: 'Akcje zarobkowe', is_expense: false, year: 2017)
pozostale_2017 = Category.create!(name: 'Pozostałe', is_expense: false, year: 2017)
jeden_procent_2017 = Category.create!(name: '1%', is_expense: false, is_one_percent: true, year: 2017)
wyposazenie_2017 = Category.create!(name: 'Wyposażenie', is_expense: true, year: 2017)
materialy_2017 = Category.create!(name: 'Materiały', is_expense: true, year: 2017)
wyzywienie_2017 = Category.create!(name: 'Wyżywienie', is_expense: true, year: 2017)
uslugi_2017 = Category.create!(name: 'Usługi', is_expense: true, year: 2017)
transport_2017 = Category.create!(name: 'Transport', is_expense: true, year: 2017)
czynsz_2017 = Category.create!(name: 'Czynsz, energia', is_expense: true, year: 2017)
ubezpieczenia_2017 = Category.create!(name: 'Ubezpieczenia', is_expense: true, year: 2017)
inne_2017 = Category.create!(name: 'Inne', is_expense: true, year: 2017)
wynagrodzenia_2017 = Category.create!(name: 'Wynagrodzenia', is_expense: true, year: 2017)
skladki_wydatek_2017 = Category.create!(name: 'Składki', is_expense: true, year: 2017)

# Districts
dlnsl = Group.create!(name: 'Okręg Dolnośląski')
grnsl = Group.create!(name: 'Okręg Górnośląski')
kujpom = Group.create!(name: 'Okręg Kujawsko-Pomorski')
lubel = Group.create!(name: 'Okręg Lubelski')
lodz = Group.create!(name: 'Okręg Łódzki')
mlp = Group.create!(name: 'Okręg Małopolski')
maz = Group.create!(name: 'Okręg Mazowiecki')
podkarp = Group.create!(name: 'Okręg Podkarpacki')
pomor = Group.create!(name: 'Okręg Pomorski')
plnzach = Group.create!(name: 'Okręg Północno-Zachodni')
wlp = Group.create!(name: 'Okręg Wielkopolski')
zhr = Group.create!(name: 'Związek Harcerstwa Rzeczypospolitej', subgroups: [dlnsl, grnsl, kujpom, lubel, lodz, mlp, maz, podkarp, pomor, plnzach, wlp])

dukt = Unit.create!(name: '9 ZDH Dukt')
pajaki = Unit.create!(name: '31 DH Pająki')
wiklina = Unit.create!(name: '9 ZDH Wiklina')
orleta = Unit.create!(name: '30 DH Orlęta')
wigryk = Unit.create!(name: '45 ŻDH Wigry')
zhhy = Group.create!(name: 'Zielonogórski Hufiec Harcerzy', units: [dukt, pajaki])
zhhek = Group.create!(name: 'Zielonogórski Hufiec Harcerek', units: [wiklina, orleta, wigryk])
obwzg = Group.create!(name: 'Obwód Zielonogórski', subgroups: [zhhy, zhhek])
wchhy = Group.create!(name: 'Wielkopolska Chorągiew Harcerzy', subgroups: [zhhy])
wchhek = Group.create!(name: 'Wielkopolska Chorągiew Harcerek', subgroups: [zhhek])
wlp.subgroups.push(wchhy, wchhek)

wrch1 = Unit.create!(name: '1 Wrocławska Drużyna Harcerzy')
wrch2 = Unit.create!(name: '2 Wrocławska Drużyna Harcerzy')
wrdz1 = Unit.create!(name: '1 Wrocławska Drużyna Harcerek')
wrdz2 = Unit.create!(name: '2 Wrocławska Drużyna Harcerek')
wrhhy = Group.create!(name: 'Wrocławski Hufiec Harcerzy', units: [wrch1, wrch2])
wrhhek = Group.create!(name: 'Wrocławski Hufiec Harcerek', units: [wrdz1, wrdz2])
dchhy = Group.create!(name: 'Dolnośląska Chorągiew Harcerzy', subgroups: [wrhhy])
dchhek = Group.create!(name: 'Dolnośląska Chorągiew Harcerek', subgroups: [wrhhek])
dlnsl.subgroups.push(dchhy, dchhek)

user = User.create!(email: 'dev@zhr.pl', password: 'dev@zhr.pl', confirmed_at: '2012-03-24 22:37:00', confirmation_sent_at: '2012-03-24 22:36:09', is_superadmin: true)

druzynowy_dukt = User.create!(email: 'druzynowy_dukt@zhr.com', password: 'druzynowy_dukt@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserUnitAssociation.create!(user: druzynowy_dukt, unit: dukt, can_view_entries: true, can_manage_entries: true)
UserUnitAssociation.create!(user: druzynowy_dukt, unit: pajaki, can_view_entries: true)

druzynowy_pajaki = User.create!(email: 'druzynowy_pajaki@zhr.com', password: 'druzynowy_pajaki@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserUnitAssociation.create!(user: druzynowy_pajaki, unit: pajaki, can_view_entries: true, can_manage_entries: true)

druzynowa_wiklina = User.create!(email: 'druzynowa_wiklina@zhr.com', password: 'druzynowa_wiklina@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserUnitAssociation.create!(user: druzynowa_wiklina, unit: wiklina, can_view_entries: true, can_manage_entries: true)

druzynowa_orleta = User.create!(email: 'druzynowa_orleta@zhr.com', password: 'druzynowa_orleta@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserUnitAssociation.create!(user: druzynowa_orleta, unit: orleta, can_view_entries: true, can_manage_entries: true)

druzynowa_wigryk = User.create!(email: 'druzynowa_wigryk@zhr.com', password: 'druzynowa_wigryk@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserUnitAssociation.create!(user: druzynowa_wigryk, unit: wigryk, can_view_entries: true, can_manage_entries: true)

hufcowyzg = User.create!(email: 'hufcowy_zg@zhr.com', password: 'hufcowy_zg@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserGroupAssociation.create!(user: hufcowyzg, group: zhhy, can_view_entries: true)
UserUnitAssociation.create!(user: hufcowyzg, unit: dukt, can_view_entries: true, can_manage_entries: true)

hufcowazg = User.create!(email: 'hufcowa_zg@zhr.com', password: 'hufcowa_zg@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserGroupAssociation.create!(user: hufcowazg, group: zhhek, can_view_entries: true)
UserUnitAssociation.create!(user: hufcowazg, unit: orleta, can_view_entries: true, can_manage_entries: true)

skarbnik_wlp = User.create!(email: 'skarbnik_wlp@zhr.com', password: 'skarbnik_wlp@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserGroupAssociation.create!(user: skarbnik_wlp, group: wlp, can_view_entries: true, can_manage_entries: true, can_close_journals: true, can_manage_users: true, can_manage_units: true, can_manage_groups: true)

druzynowy_wrch1 = User.create!(email: 'druzynowy_wrch1@zhr.com', password: 'druzynowy_wrch1@zhr.com', confirmed_at: '2013-08-26 01:01:01', confirmation_sent_at: '2013-08-26 20:00:00')
UserUnitAssociation.create!(user: druzynowy_wrch1, unit: wrch1, can_view_entries: true, can_manage_entries: true)

druzynowy_wrch2 = User.create!(email: 'druzynowy_wrch2@zhr.com', password: 'druzynowy_wrch2@zhr.com', confirmed_at: '2013-08-26 01:01:01', confirmation_sent_at: '2013-08-26 20:00:00')
UserUnitAssociation.create!(user: druzynowy_wrch2, unit: wrch2, can_view_entries: true, can_manage_entries: true)

druzynowa_wrdz1 = User.create!(email: 'druzynowa_wrdz1@zhr.com', password: 'druzynowa_wrdz1@zhr.com', confirmed_at: '2013-08-26 01:01:01', confirmation_sent_at: '2013-08-26 20:00:00')
UserUnitAssociation.create!(user: druzynowa_wrdz1, unit: wrdz1, can_view_entries: true, can_manage_entries: true)

druzynowa_wrdz2 = User.create!(email: 'druzynowa_wrdz2@zhr.com', password: 'druzynowa_wrdz2@zhr.com', confirmed_at: '2013-08-26 01:01:01', confirmation_sent_at: '2013-08-26 20:00:00')
UserUnitAssociation.create!(user: druzynowa_wrdz2, unit: wrdz2, can_view_entries: true, can_manage_entries: true)

hufcowywr = User.create!(email: 'hufcowy_wr@zhr.com', password: 'hufcowy_wr@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserGroupAssociation.create!(user: hufcowywr, group: wrhhy, can_view_entries: true)

hufcowawr = User.create!(email: 'hufcowa_wr@zhr.com', password: 'hufcowa_wr@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserGroupAssociation.create!(user: hufcowawr, group: wrhhek, can_view_entries: true)

skarbnik_dlnsl = User.create!(email: 'skarbnik_dlnsl@zhr.com', password: 'skarbnik_dlnsl@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserGroupAssociation.create!(user: skarbnik_dlnsl, group: dlnsl, can_view_entries: true, can_manage_entries: true, can_close_journals: true, can_manage_users: true, can_manage_units: true, can_manage_groups: true)

skarbnik_zachodu = User.create!(email: 'skarbnik_zachodu@zhr.com', password: 'skarbnik_zachodu@zhr.com', confirmed_at: '2013-02-23 20:02:00', confirmation_sent_at: '2013-02-23 20:00:00')
UserGroupAssociation.create!(user: skarbnik_zachodu, group: wlp, can_view_entries: true, can_manage_entries: true, can_close_journals: true, can_manage_users: true, can_manage_units: false, can_manage_groups: false)
UserGroupAssociation.create!(user: skarbnik_zachodu, group: dlnsl, can_view_entries: true, can_manage_entries: true, can_close_journals: true, can_manage_users: true, can_manage_units: true, can_manage_groups: true)

finance = JournalType.create!(id: JournalType::FINANCE_TYPE_ID, name: "Książka finansowa", is_default: true)
bank = JournalType.create!(id: JournalType::BANK_TYPE_ID, name: "Książka bankowa")

dukt2010f = Journal.create!(year: 2010, journal_type: finance, unit: dukt, is_open: false, initial_balance: 9.00, initial_balance_one_percent: 9.00)
dukt2010b = Journal.create!(year: 2010, journal_type: bank, unit: dukt, is_open: false)
dukt2011f = Journal.create!(year: 2011, journal_type: finance, unit: dukt, is_open: false)
dukt2011b = Journal.create!(year: 2011, journal_type: bank, unit: dukt, is_open: false)
dukt2012f = Journal.create!(year: 2012, journal_type: finance, unit: dukt, is_open: true, initial_balance: 9.00, initial_balance_one_percent: 6.00)
dukt2012b = Journal.create!(year: 2012, journal_type: bank, unit: dukt, is_open: true)
pajaki2010f = Journal.create!(year: 2010, journal_type: finance, unit: pajaki, is_open: false)
pajaki2010b = Journal.create!(year: 2010, journal_type: bank, unit: pajaki, is_open: false)
pajaki2011f = Journal.create!(year: 2011, journal_type: finance, unit: pajaki, is_open: false)
pajaki2011b = Journal.create!(year: 2011, journal_type: bank, unit: pajaki, is_open: false)
wiklina1997f = Journal.create!(year: 1997, journal_type: finance, unit: wiklina, is_open: false)
wiklina1997b = Journal.create!(year: 1997, journal_type: bank, unit: wiklina, is_open: false)
wiklina1998f = Journal.create!(year: 1998, journal_type: finance, unit: wiklina, is_open: false)
wiklina1998b = Journal.create!(year: 1998, journal_type: bank, unit: wiklina, is_open: false)
wigryk2011f = Journal.create!(year: 2011, journal_type: finance, unit: wigryk, is_open: true, initial_balance: 12.34)
wigryk2011b = Journal.create!(year: 2011, journal_type: bank, unit: wigryk, is_open: true, initial_balance: 12.34)

darowizna = Entry.new(date: '2012-01-01', name: 'entry 1: darowizna', document_number: 'ey1', journal: dukt2012f, is_expense: false)
akcja_i_darowizna = Entry.new(date: '2012-01-01', name: 'entry 2: akcja, darowizna', document_number: 'ntr2', journal: dukt2012f, is_expense: false)
wyposazenie = Entry.new(date: '2012-01-01', name: 'entry 3: wyposazenie', document_number: 'fv4', journal: dukt2012f, is_expense: true)
transport = Entry.new(date: '2011-01-01', name: 'entry 4: transport', document_number: 'trnsprtdrwn', journal: wigryk2011b, is_expense: false)
wynagrodzenie_i_wyposazenie = Entry.new(date: '2011-01-01', name: 'entry 5: darowizna, wyposazenie', document_number: 'dar34', journal: wigryk2011b, is_expense: true)

darowizna.items << Item.create!(amount: 1, category: darowizny_2012)
akcja_i_darowizna.items << Item.create!(amount: 2, category: akcje_zarobkowe_2012)
akcja_i_darowizna.items << Item.create!(amount: 3, category: darowizny_2012)
wyposazenie.items << Item.create!(amount: 4, amount_one_percent: 2, category: wyposazenie_2012)
wyposazenie.items << Item.create!(amount: 3, amount_one_percent: 1, category: uslugi_2012)
transport.items << Item.create!(amount: 5, category: wynagrodzenia_2011)
wynagrodzenie_i_wyposazenie.items << Item.create!(amount: 6, category: wynagrodzenia_2011)
wynagrodzenie_i_wyposazenie.items << Item.create!(amount: 7, category: wyposazenie_2011)

darowizna.save!
akcja_i_darowizna.save!
wyposazenie.save!
transport.save!
wynagrodzenie_i_wyposazenie.save!
