name: ziher-demo

services:
  demo-db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  demo:
    image: ziher/app:2025.06.19-6d5f9fa
    restart: always
    entrypoint: /ziher/entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      demo-db:
        condition: service_healthy
    environment:
      RAILS_RELATIVE_URL_ROOT: /demo
      RAILS_ENV: production
      ZIHER_APP_NAME: Demo
      ZIHER_DB_HOST: demo-db
      ZIHER_DB_NAME: ziherdemo
      ZIHER_DB_USERNAME: ziherdemo
      ZIHER_DB_PASSWORD: ziherdemo
    volumes:
      - ./entrypoint.sh:/ziher/entrypoint.sh
      - ./seeds.rb:/ziher/db/seeds.rb
