name: Build and test pull requests

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_DB: ziher_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Build ZiHeR container
        run: ./build.sh

      # - name: Enable Postgres
      #   run: sudo systemctl start postgresql

      # this can be replaced with a built-in postgres once we upgrade it
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md
      # - name: Set up PostgreSQL
      #   uses: Harmon758/postgresql-action@v1.0.0
      #   with:
      #     postgres-version: '10'
      #     username: 'postgres'
      #     password: 'postgres'
      #     database: 'ziher_test'

      - name: install dev postgres library
        run: sudo apt install --yes libpq-dev

      - name: Create test database
        run: docker run --rm ziher/app:latest rake db:schema:load RAILS_ENV=test
        # run: docker run --rm ziher/app:latest rake db:create db:schema:load RAILS_ENV=test

      - name: Run tests inside the container
        run: docker run --rm ziher/app:latest rake test

      # - name: Login to Docker Hub
      #   run: docker login -u ${DOCKER_HUB_LOGIN} -p ${DOCKER_HUB_TOKEN}
      #   env:
      #     DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
      #     DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      # - name: Push Docker Hub
      #   run: ./release.sh
