name: Build and publish ZiHeR prod app image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v4

      - name: Build ZiHeR container
        run: make build-prod CACHE_FROM=type=gha,scope=ziher-prod CACHE_TO=type=gha,scope=ziher-prod,mode=max

      - name: Login to Docker Hub
        run: docker login -u ${DOCKER_HUB_LOGIN} -p ${DOCKER_HUB_TOKEN}
        env:
          DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker Hub
        run: ./release.sh prod
